"""add group_id to post table

Revision ID: e8b34c1f4e8e
Revises: 92d11e6c7699
Create Date: 2024-05-15 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b34c1f4e8e'
down_revision = '92d11e6c7699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_post_group_id', 'group', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_group_id', type_='foreignkey')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
